spring:
    datasource:
        password: 
        url: jdbc:h2:mem:testdb
        username: sa
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: update
            
keycloak:
    auth-server-url: http://localhost:8180/auth
    realm: SpringBootKeycloak
    resource: mercado-livre-app
    public-client: true